# Generated by Django 4.0.4 on 2022-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_userprofile_otp_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donation',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='blood_units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='hapetitis_b',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='hapetitis_c',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='hiv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='syphilis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
