# Generated by Django 4.0.4 on 2022-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0005_blood_donation_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donation',
            name='recieve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
