# Generated by Django 4.1.1 on 2022-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0008_testpredict'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
